import { PersonalityTypeDefinition } from "@/types/diagnosis";

import type { TypeGroupId } from "./groups";

export interface ExtendedPersonalityTypeDefinition extends PersonalityTypeDefinition {
  catchphrase: string;
  emoji: string;
  badCompatibleTypes: string[];
  tags: string[];
  /**
   * カナ愛称（bio・口頭伝播用の識別トークン）。末尾の「型」は含めない。
   * 表示は必ず typeToken() を通し、`ライオ型` の形に組み立てる
   * （`ライオ型の人` `ライオ型同士` のような語形変化に対応するため）。
   */
  nickname: string;
  /** 所属群。群名と再定義の一行は components/brand/group-badge.tsx が一体で保持する */
  group: TypeGroupId;
}

/** 表示用の識別トークン（例: `ライオ型`）。愛称を単独で画面に出さないための唯一の入口 */
export const typeToken = (type: Pick<ExtendedPersonalityTypeDefinition, "nickname">): string =>
  `${type.nickname}型`;

export const personalityTypes: ExtendedPersonalityTypeDefinition[] = [
  {
    id: "creative-leader",
    typeName: "創造的リーダー",
    nickname: "ライオ",
    group: "ignition",
    catchphrase: "全人類を巻き込むアイデアマン",
    emoji: "🦁",
    tags: ["#カリスマ", "#新しもの好き", "#飽き性"],
    description: "「これ面白そう！」だけで世界を変える勢いがある人。計画性はゼロだけど、周りが勝手についてくる謎の魅力持ち。",
    dominantTraits: ["創造性", "外向性", "開放性"],
    characteristics: {
      strengths: ["圧倒的な行動力", "人をワクワクさせる", "逆境に強い"],
      growthAreas: ["計画を立てるのが苦手", "細かい事務作業で死ぬ"],
      communication: "とにかく熱い。主語がデカい。",
      workStyle: "チームの先頭で旗を振る特攻隊長",
      relationships: "「ついてこい！」で引っ張る",
    },
    compatibleTypes: ["social-innovator", "charismatic-enthusiast", "visionary-executor"],
    badCompatibleTypes: ["reliable-organizer", "conscientious-guardian", "methodical-thinker"],
  },
  {
    id: "social-innovator",
    typeName: "社交的革新者",
    nickname: "ウニコ",
    group: "ignition",
    catchphrase: "人脈お化けのトレンドセッター",
    emoji: "🦄",
    tags: ["#コミュ力", "#流行の最先端", "#広く浅く"],
    description: "知り合いの知り合いは全員友達。流行りの店やイベントは全部把握してる。一人でいると死ぬタイプ。",
    dominantTraits: ["社交性", "オープンマインド", "協調性"],
    characteristics: {
      strengths: ["誰とでも仲良くなれる", "場の空気を読む天才", "情報通"],
      growthAreas: ["一人作業ができない", "八方美人になりがち"],
      communication: "ノリが良い。レスが早い。",
      workStyle: "人を繋げて新しい価値を生む",
      relationships: "友達100人できるかな",
    },
    compatibleTypes: ["creative-leader", "social-organizer", "active-communicator"],
    badCompatibleTypes: ["solvent-intellectual", "introverted-artist", "quiet-observer"],
  },
  {
    id: "charismatic-enthusiast",
    typeName: "カリスマ的熱狂家",
    nickname: "フレア",
    group: "ignition",
    catchphrase: "情熱だけで生きる暴走機関車",
    emoji: "🔥",
    tags: ["#熱血", "#直感", "#後先考えない"],
    description: "「やるぞ！」って決めたら壁をぶち破ってでも進む。周りはハラハラするけど、なぜか憎めないリーダー。",
    dominantTraits: ["カリスマ", "行動力", "楽観性"],
    characteristics: {
      strengths: ["迷わない決断力", "周りを奮い立たせる", "メンタル最強"],
      growthAreas: ["人の話を聞かない", "ブレーキが壊れてる"],
      communication: "声がデカい。圧がすごい。",
      workStyle: "勢いで突破する",
      relationships: "熱狂的なファンを作る",
    },
    compatibleTypes: ["creative-leader", "visionary-executor", "practical-leader"],
    badCompatibleTypes: ["quiet-observer", "philosophical-curator", "depth-explorer"],
  },
  {
    id: "exploratory-connector",
    typeName: "探求的コネクター",
    nickname: "ジェット",
    group: "ignition",
    catchphrase: "世界中が庭の自由人",
    emoji: "✈️",
    tags: ["#旅人", "#自由奔放", "#束縛無理"],
    description: "気づいたら海外にいるタイプ。新しい場所、新しい人が大好き。ルーティンワークは拷問と同じ。",
    dominantTraits: ["探求心", "越境性", "適応力"],
    characteristics: {
      strengths: ["適応力が異常", "偏見がない", "サバイバル能力"],
      growthAreas: ["一つの場所に留まれない", "貯金が苦手"],
      communication: "オープンでフレンドリー",
      workStyle: "場所にとらわれない働き方",
      relationships: "束縛しない関係がベスト",
    },
    compatibleTypes: ["social-innovator", "enthusiastic-networker", "relational-ambassador"],
    badCompatibleTypes: ["steady-specialist", "reliable-organizer", "conscientious-guardian"],
  },
  {
    id: "visionary-executor",
    typeName: "ビジョナリー実行者",
    nickname: "シロ",
    group: "ignition",
    catchphrase: "夢を現実に変える最強の司令塔",
    emoji: "🏰",
    tags: ["#野心家", "#戦略", "#結果主義"],
    description: "デカい夢を語るだけじゃなく、ちゃんと実現するプランも持ってる。一番敵に回したくないタイプ。",
    dominantTraits: ["遠見", "実行力", "統率力"],
    characteristics: {
      strengths: ["全体を俯瞰する力", "組織を動かす力", "目的達成への執念"],
      growthAreas: ["冷酷に見られがち", "現場の気持ちを無視する"],
      communication: "論理的で説得力がある",
      workStyle: "盤面を支配して勝利する",
      relationships: "共に高みを目指す同志",
    },
    compatibleTypes: ["creative-leader", "charismatic-enthusiast", "practical-leader"],
    badCompatibleTypes: ["entertaining-creator", "poetic-dreamer", "contemplative-sage"],
  },
  {
    id: "entertaining-creator",
    typeName: "エンターテイニングクリエイター",
    nickname: "フェス",
    group: "ignition",
    catchphrase: "歩くエンターテイメント",
    emoji: "🎉",
    tags: ["#ムードメーカー", "#お笑い", "#目立ちたがり"],
    description: "クラスに一人はいる「面白いヤツ」。笑わせるためなら何でもする。静かな空間は耐えられない。",
    dominantTraits: ["創造性", "エンターテイメント性", "社交性"],
    characteristics: {
      strengths: ["場を盛り上げる", "クリエイティブな発想", "サービス精神"],
      growthAreas: ["真面目な話が苦手", "空回りすることもある"],
      communication: "ユーモアたっぷりで楽しい",
      workStyle: "遊び心を忘れない",
      relationships: "一緒にいて飽きない関係",
    },
    compatibleTypes: ["social-innovator", "active-communicator", "enthusiastic-networker"],
    badCompatibleTypes: ["solvent-intellectual", "conscientious-guardian", "methodical-thinker"],
  },
  {
    id: "introverted-artist",
    typeName: "内省的芸術家",
    nickname: "アトリ",
    group: "settling",
    catchphrase: "孤独を愛する孤高の天才",
    emoji: "🎨",
    tags: ["#マイワールド", "#繊細", "#こだわり"],
    description: "自分の世界観が確立されている。大人数でワイワイするのは苦手だけど、心を許した人にはめっちゃ喋る。",
    dominantTraits: ["内省", "芸術性", "感受性"],
    characteristics: {
      strengths: ["独自のセンス", "深い思考力", "高い集中力"],
      growthAreas: ["世渡りが下手", "傷つきやすい"],
      communication: "言葉より作品で語る",
      workStyle: "一人で没頭して生み出す",
      relationships: "魂で繋がる深い関係",
    },
    compatibleTypes: ["philosophical-curator", "depth-explorer", "poetic-dreamer"],
    badCompatibleTypes: ["social-innovator", "charismatic-enthusiast", "active-communicator"],
  },
  {
    id: "philosophical-curator",
    typeName: "哲学的キュレーター",
    nickname: "ビブリ",
    group: "settling",
    catchphrase: "真理を見抜くインテリ",
    emoji: "📚",
    tags: ["#博識", "#冷静", "#分析"],
    description: "常に「なぜ？」と考えている。知識欲がすごくて、話すと面白いけどちょっと理屈っぽい。",
    dominantTraits: ["哲学性", "選別眼", "知的探求"],
    characteristics: {
      strengths: ["本質を見抜く", "豊富な知識", "冷静な判断"],
      growthAreas: ["行動に移すのが遅い", "理屈で詰めがち"],
      communication: "知的で深みのある会話",
      workStyle: "情報の編集と意味づけ",
      relationships: "知的な刺激を与え合う",
    },
    compatibleTypes: ["introverted-artist", "depth-explorer", "solvent-intellectual"],
    badCompatibleTypes: ["charismatic-enthusiast", "entertaining-creator", "social-organizer"],
  },
  {
    id: "depth-explorer",
    typeName: "深淵探求者",
    nickname: "ノクタ",
    group: "settling",
    catchphrase: "闇をも愛する哲学者",
    emoji: "🌑",
    tags: ["#ミステリアス", "#洞察力", "#深読み"],
    description: "表面的な会話は苦手。「人生とは」みたいな話を朝までできる。ミステリアスな雰囲気が人を惹きつける。",
    dominantTraits: ["深さ", "探求心", "直感的理解"],
    characteristics: {
      strengths: ["嘘を見抜く力", "深い共感力", "問題の根本解決"],
      growthAreas: ["考えすぎて病む", "社交辞令が言えない"],
      communication: "言葉の裏を読む",
      workStyle: "根本原因の究明",
      relationships: "嘘のない真実の関係",
    },
    compatibleTypes: ["introverted-artist", "philosophical-curator", "contemplative-sage"],
    badCompatibleTypes: ["entertaining-creator", "active-communicator", "enthusiastic-networker"],
  },
  {
    id: "poetic-dreamer",
    typeName: "詩的夢想家",
    nickname: "ルナ",
    group: "settling",
    catchphrase: "夢と現実の狭間で生きるロマンチスト",
    emoji: "🌙",
    tags: ["#妄想", "#ロマンチック", "#天然"],
    description: "よく空を見上げてる。現実的な事務作業は苦手だけど、美しい言葉や物語を紡ぐ才能はピカイチ。",
    dominantTraits: ["詩的感覚", "想像力", "感受性"],
    characteristics: {
      strengths: ["豊かな想像力", "美しい表現力", "純粋な心"],
      growthAreas: ["現実逃避しがち", "お金の管理ができない"],
      communication: "比喩やポエムが多い",
      workStyle: "夢を形にする仕事",
      relationships: "おとぎ話のような恋",
    },
    compatibleTypes: ["introverted-artist", "depth-explorer", "contemplative-sage"],
    badCompatibleTypes: ["visionary-executor", "practical-leader", "conscientious-guardian"],
  },
  {
    id: "solvent-intellectual",
    typeName: "孤独な知識人",
    nickname: "ソロ",
    group: "settling",
    catchphrase: "感情より論理のサイボーグ",
    emoji: "💻",
    tags: ["#論理的", "#効率厨", "#一人が楽"],
    description: "感情論は通じない。「それって合理的？」が口癖。冷たく見えるけど、実は誠実で嘘をつかないだけ。",
    dominantTraits: ["孤独", "知性探求", "論理的思考"],
    characteristics: {
      strengths: ["圧倒的な論理性", "客観的な分析", "効率化"],
      growthAreas: ["人の気持ちがわからない", "冷徹に見える"],
      communication: "結論から話す",
      workStyle: "システム構築と最適化",
      relationships: "依存しない自立した関係",
    },
    compatibleTypes: ["philosophical-curator", "contemplative-sage", "methodical-thinker"],
    badCompatibleTypes: ["social-innovator", "entertaining-creator", "social-organizer"],
  },
  {
    id: "contemplative-sage",
    typeName: "静観的賢者",
    nickname: "マッチャ",
    group: "settling",
    catchphrase: "全てを悟った仙人",
    emoji: "🍵",
    tags: ["#穏やか", "#達観", "#相談役"],
    description: "実年齢より精神年齢が30歳くらい上。何が起きても動じない。みんなの相談役ポジション。",
    dominantTraits: ["静観", "知恵", "不動心"],
    characteristics: {
      strengths: ["精神的安定感", "的確なアドバイス", "広い視野"],
      growthAreas: ["刺激に欠ける", "行動が遅い"],
      communication: "聞き上手で穏やか",
      workStyle: "長期的な視点での判断",
      relationships: "安心感を与える存在",
    },
    compatibleTypes: ["philosophical-curator", "depth-explorer", "solvent-intellectual"],
    badCompatibleTypes: ["charismatic-enthusiast", "active-communicator", "enthusiastic-networker"],
  },
  {
    id: "practical-leader",
    typeName: "実践的リーダー",
    nickname: "ゲンバ",
    group: "chain",
    catchphrase: "口より先に手が動く現場監督",
    emoji: "👷",
    tags: ["#頼れる", "#現実的", "#兄貴肌"],
    description: "理想論より「で、どうすんの？」派。トラブルが起きてもパニックにならず、淡々と解決する頼れる存在。",
    dominantTraits: ["実践性", "リーダーシップ", "現実感覚"],
    characteristics: {
      strengths: ["現場での対応力", "面倒見が良い", "確実な成果"],
      growthAreas: ["新しい変化を嫌う", "柔軟性に欠ける"],
      communication: "具体的で指示が明確",
      workStyle: "着実にタスクをこなす",
      relationships: "背中で語る信頼関係",
    },
    compatibleTypes: ["visionary-executor", "steady-specialist", "reliable-organizer"],
    badCompatibleTypes: ["exploratory-connector", "poetic-dreamer", "philosophical-curator"],
  },
  {
    id: "social-organizer",
    typeName: "社交的組織者",
    nickname: "カンジ",
    group: "chain",
    catchphrase: "幹事やらせたら日本一",
    emoji: "📋",
    tags: ["#世話焼き", "#しっかり者", "#調整役"],
    description: "飲み会の幹事、旅行の計画、全部やってくれる神。みんなが楽しめるように影でめちゃくちゃ動いてる。",
    dominantTraits: ["社交性", "組織力", "調整力"],
    characteristics: {
      strengths: ["段取り力", "気配り", "調整能力"],
      growthAreas: ["自分の楽しみを後回し", "完璧を求めすぎる"],
      communication: "丁寧で連絡がマメ",
      workStyle: "チームの潤滑油",
      relationships: "みんなのお母さん的存在",
    },
    compatibleTypes: ["social-innovator", "community-builder", "relational-ambassador"],
    badCompatibleTypes: ["depth-explorer", "solvent-intellectual", "dedicated-crafter"],
  },
  {
    id: "active-communicator",
    typeName: "能動的コミュニケーター",
    nickname: "メガホ",
    group: "chain",
    catchphrase: "沈黙を許さないマシンガントーカー",
    emoji: "📢",
    tags: ["#おしゃべり", "#積極的", "#ポジティブ"],
    description: "とにかく喋る。沈黙が怖い。でも、その明るさで場を一気に盛り上げる特攻隊長。",
    dominantTraits: ["能動性", "伝達力", "社交性"],
    characteristics: {
      strengths: ["発信力", "初対面でも平気", "場を明るくする"],
      growthAreas: ["人の話を聞いてない", "デリカシーがない時も"],
      communication: "テンポが良く途切れない",
      workStyle: "広報やプレゼン担当",
      relationships: "会話が絶えない楽しい関係",
    },
    compatibleTypes: ["social-innovator", "entertaining-creator", "enthusiastic-networker"],
    badCompatibleTypes: ["introverted-artist", "solvent-intellectual", "quiet-observer"],
  },
  {
    id: "community-builder",
    typeName: "コミュニティ・ビルダー",
    nickname: "ムラオ",
    group: "chain",
    catchphrase: "みんなの居場所を作る優しい村長",
    emoji: "🏡",
    tags: ["#優しい", "#包容力", "#平和主義"],
    description: "争いが嫌い。みんなが仲良くできる場所を作りたい人。あなたの周りには自然と人が集まる。",
    dominantTraits: ["コミュニティ", "建設性", "社会的気配り"],
    characteristics: {
      strengths: ["安心感を作る", "対立を仲裁する", "継続的な関係構築"],
      growthAreas: ["厳しいことが言えない", "八方美人"],
      communication: "穏やかで否定的でない",
      workStyle: "心理的安全性の確保",
      relationships: "家族のような温かい関係",
    },
    compatibleTypes: ["social-organizer", "relational-ambassador", "social-innovator"],
    badCompatibleTypes: ["charismatic-enthusiast", "visionary-executor", "solvent-intellectual"],
  },
  {
    id: "enthusiastic-networker",
    typeName: "熱心なネットワーカー",
    nickname: "スニカ",
    group: "chain",
    catchphrase: "フットワーク軽すぎの冒険家",
    emoji: "👟",
    tags: ["#行動力", "#好奇心", "#人好き"],
    description: "「面白そう！」で即参加。いろんなコミュニティに顔を出して、面白い人を繋げるのが生きがい。",
    dominantTraits: ["ネットワーク", "熱心さ", "社交的エネルギー"],
    characteristics: {
      strengths: ["情報収集力", "顔が広い", "行動が早い"],
      growthAreas: ["飽きっぽい", "関係が浅くなりがち"],
      communication: "フレンドリーで壁がない",
      workStyle: "新規開拓とマッチング",
      relationships: "刺激的でアクティブな関係",
    },
    compatibleTypes: ["social-innovator", "exploratory-connector", "active-communicator"],
    badCompatibleTypes: ["steady-specialist", "reliable-organizer", "conscientious-guardian"],
  },
  {
    id: "relational-ambassador",
    typeName: "関係性大使",
    nickname: "タイシ",
    group: "chain",
    catchphrase: "敵を作らない最強の外交官",
    emoji: "🤝",
    tags: ["#バランス感覚", "#世渡り上手", "#中立"],
    description: "どんなタイプの人ともうまくやれる。板挟みになってもニコニコしながら解決策を見つける天才。",
    dominantTraits: ["外交性", "調整力", "文化的理解"],
    characteristics: {
      strengths: ["交渉力", "好感度が高い", "トラブル回避"],
      growthAreas: ["本音が見えない", "決定を避ける"],
      communication: "相手を立てる",
      workStyle: "利害調整と合意形成",
      relationships: "スマートで大人な関係",
    },
    compatibleTypes: ["social-organizer", "community-builder", "social-innovator"],
    badCompatibleTypes: ["solvent-intellectual", "conscientious-guardian", "methodical-thinker"],
  },
  {
    id: "steady-specialist",
    typeName: "堅実な専門家",
    nickname: "バリア",
    group: "inert",
    catchphrase: "石橋を叩いて渡るプロフェッショナル",
    emoji: "🛡️",
    tags: ["#真面目", "#慎重", "#安定"],
    description: "派手さはないけど、任された仕事は絶対にミスらない。組織に一人は欲しい守護神。",
    dominantTraits: ["堅実性", "専門性", "信頼性"],
    characteristics: {
      strengths: ["ミスのなさ", "責任感", "継続力"],
      growthAreas: ["融通が利かない", "変化が怖い"],
      communication: "事実ベースで正確",
      workStyle: "着実な積み上げ",
      relationships: "裏切らない誠実な関係",
    },
    compatibleTypes: ["reliable-organizer", "dedicated-crafter", "methodical-thinker"],
    badCompatibleTypes: ["creative-leader", "exploratory-connector", "entertaining-creator"],
  },
  {
    id: "reliable-organizer",
    typeName: "信頼できる整理者",
    nickname: "フォルダ",
    group: "inert",
    catchphrase: "散らかった部屋も人生も片付ける",
    emoji: "🗂️",
    tags: ["#几帳面", "#整理整頓", "#ルール"],
    description: "カオスな状況を整理するのが得意。ルールや手順が決まっていると安心する。掃除好き。",
    dominantTraits: ["整理整頓", "信頼性", "秩序"],
    characteristics: {
      strengths: ["管理能力", "効率化", "秩序の維持"],
      growthAreas: ["イレギュラーに弱い", "他人にも厳しい"],
      communication: "順序立てて話す",
      workStyle: "マニュアル化と運用",
      relationships: "予測可能で安心できる関係",
    },
    compatibleTypes: ["steady-specialist", "conscientious-guardian", "practical-leader"],
    badCompatibleTypes: ["creative-leader", "exploratory-connector", "poetic-dreamer"],
  },
  {
    id: "quiet-observer",
    typeName: "静かな観察者",
    nickname: "レーダ",
    group: "inert",
    catchphrase: "全てを見透かすステルス探偵",
    emoji: "🕵️",
    tags: ["#聞き上手", "#洞察力", "#無口"],
    description: "自分からは話さないけど、周りのことは全部把握してる。「実はあの時こう思ってた」が的確すぎて怖い。",
    dominantTraits: ["観察力", "冷静さ", "分析的思考"],
    characteristics: {
      strengths: ["空気読み力", "客観的視点", "秘密を守る"],
      growthAreas: ["存在感が薄くなる", "意見を言わない"],
      communication: "聞き役徹",
      workStyle: "データの監視と分析",
      relationships: "多くを語らずとも通じ合う",
    },
    compatibleTypes: ["introverted-artist", "philosophical-curator", "solvent-intellectual"],
    badCompatibleTypes: ["creative-leader", "social-innovator", "charismatic-enthusiast"],
  },
  {
    id: "dedicated-crafter",
    typeName: "専心した職人",
    nickname: "タクミ",
    group: "inert",
    catchphrase: "一つの道を極める求道者",
    emoji: "🔨",
    tags: ["#オタク", "#集中力", "#頑固"],
    description: "興味のあることには寝食を忘れて没頭する。それ以外はどうでもいい。現代の職人。",
    dominantTraits: ["没入力", "一途さ", "技術追求"],
    characteristics: {
      strengths: ["圧倒的なスキル", "妥協しない", "専門知識"],
      growthAreas: ["視野が狭い", "協調性不足"],
      communication: "専門用語が多い",
      workStyle: "ソロワークでの深掘り",
      relationships: "価値観を共有できる少数の人",
    },
    compatibleTypes: ["steady-specialist", "methodical-thinker", "solvent-intellectual"],
    badCompatibleTypes: ["social-organizer", "active-communicator", "social-innovator"],
  },
  {
    id: "conscientious-guardian",
    typeName: "良心的守護者",
    nickname: "テンビン",
    group: "inert",
    catchphrase: "ルールと伝統を守る最後の砦",
    emoji: "⚖️",
    tags: ["#正義感", "#保守的", "#厳格"],
    description: "曲がったことが大嫌い。約束は絶対守るし、守らせる。厳しいけど一番信頼できる人。",
    dominantTraits: ["良心", "守護者", "安定性"],
    characteristics: {
      strengths: ["倫理観", "責任感", "組織の安定化"],
      growthAreas: ["頭が固い", "新しいものへの拒絶"],
      communication: "厳格だが愛がある",
      workStyle: "リスク管理とコンプラ遵守",
      relationships: "規律ある清廉な関係",
    },
    compatibleTypes: ["steady-specialist", "reliable-organizer", "practical-leader"],
    badCompatibleTypes: ["creative-leader", "exploratory-connector", "entertaining-creator"],
  },
  {
    id: "methodical-thinker",
    typeName: "方法的思考家",
    nickname: "ジョーギ",
    group: "inert",
    catchphrase: "歩く攻略本",
    emoji: "📐",
    tags: ["#計画的", "#手順重視", "#分析"],
    description: "何をするにもまずは計画から。攻略法を見つけてからゲームを始めるタイプ。無駄な動きは一切しない。",
    dominantTraits: ["体系的", "論理的", "秩序重視"],
    characteristics: {
      strengths: ["プランニング", "問題解決の最短ルート", "再現性"],
      growthAreas: ["アドリブに弱い", "面白みがない"],
      communication: "結論と理由をセットで",
      workStyle: "設計図通りの構築",
      relationships: "お互いの役割が明確な関係",
    },
    compatibleTypes: ["solvent-intellectual", "steady-specialist", "dedicated-crafter"],
    badCompatibleTypes: ["creative-leader", "entertaining-creator", "poetic-dreamer"],
  },
];
