import { PersonalityTypeDefinition } from "@/types/diagnosis";

export const personalityTypes: PersonalityTypeDefinition[] = [
  {
    id: "creative-leader",
    typeName: "創造的リーダー",
    description: "新しいアイデアを創出し、人を巻き込んで実現する能力に長けています。",
    dominantTraits: ["創造性", "外向性", "開放性"],
    characteristics: {
      strengths: ["革新的思考", "人を惹きつける魅力", "実行力"],
      growthAreas: ["計画性", "詳細への注意"],
      communication: "情熱的でビジョンを共有",
      workStyle: "チームを動かし、新たな道を開拓",
      relationships: "協力的で刺激的",
    },
    compatibleTypes: ["analytical-thinker", "steady-supporter", "creative-specialist"],
  },
  {
    id: "social-innovator",
    typeName: "社交的革新者",
    description: "人間関係を通じて新しい価値を創造し、コミュニティを活性化させます。",
    dominantTraits: ["社交性", "オープンマインド", "協調性"],
    characteristics: {
      strengths: ["ネットワーク構築", "場の空気作り", "アイデア具現化"],
      growthAreas: ["孤独な作業", "批判的思考"],
      communication: "包摂的で刺激的",
      workStyle: "協同作業で新しい価値を創造",
      relationships: "多様な人々を繋ぐハブ",
    },
    compatibleTypes: ["thoughtful-analyst", "reliable-organizer", "empathetic-connector"],
  },
  {
    id: "charismatic-enthusiast",
    typeName: "カリスマ的熱狂家",
    description: "魅力的な人間力で周りを巻き込み、困難に立ち向かうリーダーシップを発揮します。",
    dominantTraits: ["カリスマ", "行動力", "楽観性"],
    characteristics: {
      strengths: ["情熱", "決断力", "逆境回復力"],
      growthAreas: ["落ち着き", "計画的思考"],
      communication: "パワフルで感動的",
      workStyle: "情熱でチームを牽引する",
      relationships: "忠実な支持者を集める",
    },
    compatibleTypes: ["calm-strategist", "detailed-planner", "loyal-supporter"],
  },
  {
    id: "exploratory-connector",
    typeName: "探求的コネクター",
    description: "新しい場所や人々を探索し、異なる背景を持つ人々を繋げる架け橋になります。",
    dominantTraits: ["探求心", "社会的柔軟性", "適応力"],
    characteristics: {
      strengths: ["国際感覚", "異文化理解", "ネットワーク力"],
      growthAreas: ["定着力", "専門性深化"],
      communication: "多言語対応、柔軟",
      workStyle: "境界を超えたコラボレーション",
      relationships: "グローバルなネットワーク",
    },
    compatibleTypes: ["cultural-scholar", "local-specialist", "global-thinker"],
  },
  {
    id: "visionary-executor",
    typeName: "ビジョナリー実行者",
    description: "大きなビジョンを描きつつ、それを実現する具体的な戦略も立てられる理想家です。",
    dominantTraits: ["遠見", "実行力", "統率力"],
    characteristics: {
      strengths: ["戦略的思考", "チームビルディング", "目標達成"],
      growthAreas: ["現場感覚", "柔軟性"],
      communication: "偉大なビジョンを語る",
      workStyle: "大きな視点から課題を解決",
      relationships: "ビジョンを共有する同志",
    },
    compatibleTypes: ["tactical-expert", "detail-oriented", "ground-realistic"],
  },
  {
    id: "entertaining-creator",
    typeName: "エンターテイニングクリエイター",
    description: "創造性と人を楽しませる能力を兼ね備え、明るい雰囲気を作り出します。",
    dominantTraits: ["創造性", "エンターテイメント性", "社交性"],
    characteristics: {
      strengths: ["表現力", "場の雰囲気作り", "想像力"],
      growthAreas: ["計画性", "現実的感覚"],
      communication: "楽しく、インスピレーションを与える",
      workStyle: "創造的な課題解決",
      relationships: "楽しい時間を共有する仲間",
    },
    compatibleTypes: ["quiet-observer", "structured-thinker", "sincere-listener"],
  },
  {
    id: "introverted-artist",
    typeName: "内省的芸術家",
    description: "内なる世界に深く沈潜し、独自の感性で芸術的価値を生み出します。",
    dominantTraits: ["内省", "芸術性", "感受性"],
    characteristics: {
      strengths: ["深い感受性", "独創性", "集中力"],
      growthAreas: ["社交スキル", "自己主張"],
      communication: "静かで深みのある",
      workStyle: "一人の時間で創造活動",
      relationships: "深い理解を求める少数の仲間",
    },
    compatibleTypes: ["gentle-mentor", "organized-collector", "quiet-scholar"],
  },
  {
    id: "philosophical-curator",
    typeName: "哲学的キュレーター",
    description: "知識と美を厳選し、そこから深い意味と教訓を見出す思考者です。",
    dominantTraits: ["哲学性", "選別眼", "知的探求"],
    characteristics: {
      strengths: ["美的感覚", "分析力", "教養"],
      growthAreas: ["実践性", "即時判断"],
      communication: "意味深く思考誘発的",
      workStyle: "質の高い情報を整理提供",
      relationships: "知的な対話を重視する仲間",
    },
    compatibleTypes: ["practical-builder", "action-oriented", "dynamic-doer"],
  },
  {
    id: "depth-explorer",
    typeName: "深淵探求者",
    description: "物事の本質的な意味を追求し、表層的な理解を超えた深い洞察を得ます。",
    dominantTraits: ["深さ", "探求心", "直感的理解"],
    characteristics: {
      strengths: ["洞察力", "本質把握", "問題発見"],
      growthAreas: ["広さ", "社会的適応"],
      communication: "深遠で示唆に富む",
      workStyle: "深層構造から問題解決",
      relationships: "精神的な繋がりを求める",
    },
    compatibleTypes: ["surface-adaptator", "broad-connector", "flexible-adapter"],
  },
  {
    id: "poetic-dreamer",
    typeName: "詩的夢想家",
    description: "現実と夢の境界を曖昧にしながら、美しい言葉で世界を再構築します。",
    dominantTraits: ["詩的感覚", "想像力", "感受性"],
    characteristics: {
      strengths: ["言語感覚", "美的センス", "共感力"],
      growthAreas: ["現実感覚", "実用性"],
      communication: "美しく詩的に語る",
      workStyle: "創造的な思考と表現",
      relationships: "ロマンチックな精神の繋がり",
    },
    compatibleTypes: ["realistic-craftsman", "grounded-builder", "pragmatic-operator"],
  },
  {
    id: "solvent-intellectual",
    typeName: "孤独な知識人",
    description: "静かな環境で深く思考し、独自の知的体系を築く学者タイプです。",
    dominantTraits: ["孤独", "知性探求", "論理的思考"],
    characteristics: {
      strengths: ["論理性", "深い思考", "客観性"],
      growthAreas: ["社交性", "感情的表現"],
      communication: "的確で論理的",
      workStyle: "理論モデルと仮説構築",
      relationships: "知的な対話と誠実な友情",
    },
    compatibleTypes: ["social-coach", "emotional-mentor", "relationship-builder"],
  },
  {
    id: "contemplative-sage",
    typeName: "静観的賢者",
    description: "世界を静かに観察し、そこから普遍的な真理と知恵を見出します。",
    dominantTraits: ["静観", "知恵", "超越性"],
    characteristics: {
      strengths: ["観察眼", "教訓抽出", "精神的安定"],
      growthAreas: ["即時性", "変化適応"],
      communication: "静かに深い知恵を語る",
      workStyle: "長期的視点での分析助言",
      relationships: "精神的な師弟関係",
    },
    compatibleTypes: ["active-practitioner", "dynamic-learner", "practical-explorer"],
  },
  {
    id: "practical-leader",
    typeName: "実践的リーダー",
    description: "現実的な目標を掲げ、着実な実行力でチームを引率する行動家です。",
    dominantTraits: ["実践性", "リーダーシップ", "現実感覚"],
    characteristics: {
      strengths: ["実行力", "判断力", "責任感"],
      growthAreas: ["創造性", "柔軟性"],
      communication: "明確で指示的",
      workStyle: "具体的な目標達成",
      relationships: "信頼と実績ベースの関係",
    },
    compatibleTypes: ["innovative-advisor", "flexible-creator", "visionary-supporter"],
  },
  {
    id: "social-organizer",
    typeName: "社交的組織者",
    description: "人々をまとめ、イベントやコミュニティを円滑に運営する調整役です。",
    dominantTraits: ["社交性", "組織力", "調整力"],
    characteristics: {
      strengths: ["調整能力", "場作り", "ネットワーク"],
      growthAreas: ["創造性", "決断力"],
      communication: "協力的で協調的",
      workStyle: "人々をつなぎ調和を保つ",
      relationships: "広く浅い良好な関係",
    },
    compatibleTypes: ["independent-creator", "decisive-thinker", "innovative-connector"],
  },
  {
    id: "active-communicator",
    typeName: "能動的コミュニケーター",
    description: "積極的に人々と関わり、情報を効果的に伝達するビジョン伝達者です。",
    dominantTraits: ["能動性", "伝達力", "社交性"],
    characteristics: {
      strengths: ["発信力", "影響力", "対話力"],
      growthAreas: ["深さ", "独創性"],
      communication: "活発で説得力がある",
      workStyle: "情報伝達と人々の結びつき",
      relationships: "コミュニケーション中心の関係",
    },
    compatibleTypes: ["quiet-observer", "deep-thinker", "reflective-listener"],
  },
  {
    id: "community-builder",
    typeName: "コミュニティ・ビルダー",
    description: "人々が集う場を作り、協力関係を育む社会的建設家です。",
    dominantTraits: ["コミュニティ", "建設性", "社会的気配り"],
    characteristics: {
      strengths: ["場作り", "関係構築", "社会性"],
      growthAreas: ["独創性", "個別化"],
      communication: "包摂的でまとめる",
      workStyle: "協力的な環境構築",
      relationships: "社会的な繋がりを大切にする",
    },
    compatibleTypes: ["individualist-creator", "solo-achiever", "independent-thinker"],
  },
  {
    id: "enthusiastic-networker",
    typeName: "熱心なネットワーカー",
    description: "人々との繋がりを楽しみながら、広範な関係網を構築します。",
    dominantTraits: ["ネットワーク", "熱心さ", "社交的エネルギー"],
    characteristics: {
      strengths: ["関係構築", "情報収集", "協力調整"],
      growthAreas: ["深さ", "専門性"],
      communication: "活発で人を繋ぐ",
      workStyle: "人的ネットワークを活用",
      relationships: "幅広い浅い楽しい関係",
    },
    compatibleTypes: ["specialized-expert", "focused-individual", "dedicated-specialist"],
  },
  {
    id: "relational-ambassador",
    typeName: "関係性大使",
    description: "異なる組織や人々の間に立って、相互理解と協力を促進します。",
    dominantTraits: ["外交性", "調整力", "文化的理解"],
    characteristics: {
      strengths: ["交渉力", "文化的適応", "関係構築"],
      growthAreas: ["専門性", "決断の迅速性"],
      communication: "調和をもたらす外交的",
      workStyle: "中立的な架け橋役",
      relationships: "信頼に基づく長期的関係",
    },
    compatibleTypes: ["principle-advocate", "decisive-specialist", "idealist-creator"],
  },
  {
    id: "steady-specialist",
    typeName: "堅実な専門家",
    description: "一つの分野に深く特化し、着実な実績と信頼を築く職人肌です。",
    dominantTraits: ["堅実性", "専門性", "信頼性"],
    characteristics: {
      strengths: ["専門知識", "集中力", "責任感"],
      growthAreas: ["広範な適応力", "変化対応"],
      communication: "的確で信頼性がある",
      workStyle: "一つの分野を徹底的に追求",
      relationships: "信頼に基づく少数の深い関係",
    },
    compatibleTypes: ["versatile-generalist", "resourceful-innovator", "broad-minded-thinker"],
  },
  {
    id: "reliable-organizer",
    typeName: "信頼できる整理者",
    description: "物事を整理整頓し、混乱を秩序に変える確かな存在感があります。",
    dominantTraits: ["整理整頓", "信頼性", "秩序"],
    characteristics: {
      strengths: ["計画性", "実行力", "安定性"],
      growthAreas: ["柔軟性", "即応性"],
      communication: "明確で分かりやすい",
      workStyle: "システムを確立し維持する",
      relationships: "安定した信頼関係",
    },
    compatibleTypes: ["chaotic-creator", "flexible-adapter", "spontaneous-artist"],
  },
  {
    id: "quiet-observer",
    typeName: "静かな観察者",
    description: "周りを静かに観察し、本質を見抜く冷静な分析家です。",
    dominantTraits: ["観察力", "冷静さ", "分析的思考"],
    characteristics: {
      strengths: ["洞察力", "客観性", "深い思考"],
      growthAreas: ["自己表現", "積極性"],
      communication: "的確で深みがある",
      workStyle: "背景から状況を分析",
      relationships: "理解に基づく静かな関係",
    },
    compatibleTypes: ["active-communicator", "expressive-performer", "dynamic-presenter"],
  },
  {
    id: "dedicated-crafter",
    typeName: "専心した職人",
    description: "自分の仕事に没頭し、その道を極める一途な人生を送ります。",
    dominantTraits: ["職人気質", "一途さ", "技術追求"],
    characteristics: {
      strengths: ["技術力", "集中力", "こだわり"],
      growthAreas: ["社会的適応", "多様性"],
      communication: "簡潔で技術的",
      workStyle: "一つの技術の深みを追求",
      relationships: "師匠と弟子のような関係",
    },
    compatibleTypes: ["curious-generalist", "interdisciplinary-thinker", "multi-talented-creator"],
  },
  {
    id: "conscientious-guardian",
    typeName: "良心的守護者",
    description: "ルールと伝統を守りながら、人々を良心的に見守る存在です。",
    dominantTraits: ["良心", "守護者", "安定性"],
    characteristics: {
      strengths: ["誠実さ", "責任感", "公正性"],
      growthAreas: ["変化対応", "革新性"],
      communication: "誠実で落ち着いている",
      workStyle: "正当性と正義を重視",
      relationships: "誠実さと信頼に基づく関係",
    },
    compatibleTypes: ["rebellious-innovator", "flexible-rule-follower", "creative-dissenter"],
  },
  {
    id: "methodical-thinker",
    typeName: "方法的思考家",
    description: "型にはまった、体系的にアプローチする思考家です。",
    dominantTraits: ["体系的", "論理的", "秩序重視"],
    characteristics: {
      strengths: ["論理構築", "体系化", "問題解決"],
      growthAreas: ["創造性", "即時対応"],
      communication: "構造的で論理的",
      workStyle: "段階的な思考と実行",
      relationships: "論理的な信頼関係",
    },
    compatibleTypes: ["intuitive-creator", "creative-thinker", "chaotic-organizer"],
  },
];
